// GET one specific file
GET http://localhost:9000/api/files/5ed8b26e4e7960d8ba6a7be6


###

// POST a new file to the database
POST http://localhost:9000/api/files/
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="Yunnan-Manljuste.png"
Content-Type: image/png

< ./teSorter/Yunnan-Manljuste.png
--FormDataRow--

###


// POST a new product to the database with the ID of the associated file included
POST http://localhost:9000/api/products/
Content-Type: application/json

{
    "file": "5ed8b26e4e7960d8ba6a7be6",
    "title": "Yunnan Månljuste",
    "description": "Doftar av peppar och rostat havre med viss rökighet. En mycket dynamisk smak börjar kryddigt med toner av majs, men går sakta över till en lenare textur med lätt smak av rörsocker  Bryggs med fördel med 2.5g per 250ml vatten. 90°-gradigt vatten i 2 minuter. Säljs 50g/pkt.",
    "price": 239,
    "category": ["Vitt"],
    "nrInStock": 89
}

###