// GET one specific file
GET http://localhost:9000/api/files/5ed4f3f3312bb323a0958180


###

// POST a new file to the database
POST http://localhost:9000/api/files/
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
--FormDataRow--

###


// POST a new product to the database with the ID of the associated file included
POST http://localhost:9000/api/products/
Content-Type: application/json

{
    "file": "5ed4f3f3312bb323a0958180",
    "title": "Original Chai8",
    "description": "te good",
    "price": 100,
    "category": ["Koffein", "Ta bort te"],
    "nrInStock": 50
}

###