// ALL ORDER RELATED ENDPOINTS


// GET // get all orders (ex. admins overview of all placed order)
// access : Admin
GET http://localhost:9000/api/orders/
###

// GET // get one or more specific order/orders  (ex. let an admin filter orders from a specific user, or a user wants to display )
// access : Admin, User
GET http://localhost:9000/api/orders/5ed6190772b56a06ccefcfbb
###

GET http://localhost:9000/api/orders/5ecb89c1e6898b4088e3d9b5
###

// POST // post order (ex. customer places order)
// access : User
POST http://localhost:9000/api/orders/
Content-Type: application/json

{
    "user": "5ee0c53260f09830deba3c54",
    "shipping": "5ed0edba9781da7e89d7cb51",
    "productRow":[{
        "product": "5ed8aad84e7960d8ba6a7bd2",
        "qty": 2},{
        "product": "5ed8ac634e7960d8ba6a7bd6",
        "qty": 4
        }],
    "to_firstname": "Zlatan",
    "to_lastname": "Ibra",
    "to_street": "milano street",
    "to_city": "stockholm",
    "to_zip": 12345
}
###

//user_1 add
POST http://localhost:9000/api/orders/
Content-Type: application/json

{
    "user": "5ecb89c1e6898b4088e3d9b5",
    "shipping": "5ed0edb39781da7e89d7cb4f",
    "productRow":[
        {
            "product": "5ed60fb19365341918bb5b3e",
            "qty": 2
        },
        {
            "product": "5ed64be9cbdbbf4a6cb7acd7",
            "qty": 12
        },
        {
            "product": "5ed61679014caf1c608dcce2",
            "qty": 1
        },
                {
            "product": "5ed64c16cbdbbf4a6cb7acd8",
            "qty": 3
        },
        {
            "product": "5ed65b6ecbdbbf4a6cb7ace3",
            "qty": 13
        }
    ],
    "to_firstname": "Roger",
    "to_lastname": "Moore",
    "to_street": "Testgatan 18",
    "to_city": "Göteborg",
    "to_zip": 12345
}
###

// PUT // update order (ex. admin changes shippingstatus to 'sent')
// access : Admin
PATCH  http://localhost:9000/api/orders/5ecd70cbd19af824100d3065
Content-Type: application/json

{
    "isOrderShipped": true
}
###

// DELETE // no delete endpoint, because in no scenario is it relevant to delete an order from the database.
// If and order has gone through and is confirmed, removing it would never be desirable.
