
// Tells us if the user is autherised
//**********sessionAuthenticate**********

GET http://localhost:9000/session/login HTTP/1.1
###


//********LOGIN A EXISTING USER*********
POST http://localhost:9000/session/login HTTP/1.1
content-type: application/json

{
    "name": "admin",
    "password": "admin"
}

###

//******LOGOUT******
DELETE http://localhost:9000/api/logout HTTP/1.1
content-type: application/json


###
