
GET http://localhost:9000/api/shipping/ HTTP/1.1

###

//******POST 1
POST http://localhost:9000/api/shipping/ HTTP/1.1
Content-Type: application/json

{
    "companyName": "PostNord Hemleverans",
    "price": 99,
    "delivery": 1
}

###

//******POST 2
POST http://localhost:9000/api/shipping/ HTTP/1.1
Content-Type: application/json

{
    "companyName": "PostNord Ombud",
    "price": 39,
    "delivery": 3
}

###

//******POST 3
POST http://localhost:9000/api/shipping/ HTTP/1.1
Content-Type: application/json

{
    "companyName": "DB Schenker",
    "price": 0,
    "delivery": 5
}

###

