


GET http://localhost:9000/api/users/ HTTP/1.1

###

// GET ONE USER
GET http://localhost:9000/api/users/admin HTTP/1.1

###

//*********  REGISTER  Create account   ************
POST http://localhost:9000/api/users/ HTTP/1.1
content-type: application/json

{
    "name": "admin",
    "password": "admin",
    "admin": true,
    "requestsAdmin": false
}

###

POST http://localhost:9000/api/users/ HTTP/1.1
content-type: application/json

{
    "name": "user_1",
    "password": "123",
    "admin": false,
    "requestsAdmin": false
}

###

DELETE  http://localhost:9000/api/users/user HTTP/1.1


